# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eav3Wv8z22jKeRvCtKJn1f0TXWC1lb0l
"""

def telefon_narxi (belgi):
    if belgi=="samsung ultra 24":
      return "900 $"
    elif belgi== "samsung ultra 23":
      return "700 $"
    elif belgi== "samsung ultra 22":
      return "500 $"
    elif belgi== "samsung ultra 21":
      return "300 $"
    elif belgi== "samsung ultra 20":
      return "200 $"
    elif belgi== "ayfon 16 pro":
      return "1400 $"
    elif belgi== "ayfon 15 pro":
      return "1200 $"
    elif belgi== "ayfon 14 pro":
      return "1000 $"
    elif belgi== "ayfon 13 pro":
      return "800 $"
    elif belgi== "ayfon 12 pro":
      return "600 $"
    elif belgi== "ayfon 11 pro":
      return "400 $"
    elif belgi== "ayfon x s max":
      return "300 $"
    else:
      return "Sotuvchiga murojaat qiling"
belgi=input ("Telefon nomini kiriting")
natija=telefon_narxi(belgi)
print(natija)

def kasallik_tashxisi (belgi):

 if belgi=="istima":

   return "Parasetamol iching"

 elif belgi== "tish og'rig'i":

   return "Qupen iching"

 elif belgi== "qorin og'rig'i":

   return "Levomitsin"

 else:

   return "Shifokorga murojaat qiling"

belgi=input("Kasallik belgisini kiriting ")

natija=kasallik_tashxisi (belgi)

print (natija)